apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnr-resequencer-service-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: pnr-resequencer-service-pod
  template:
    metadata:
      labels:
        app: pnr-resequencer-service-pod
    spec:
      containers:
        - image: gcr.io/pnr-order-poc/pnr-resequencer-service:latest
          name: pnr-resequencer-service
            