apiVersion: apps/v1
kind: Deployment
metadata:
  name: pnr-resequencer-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pnr-resequencer-service-pod
  template:
    metadata:
      labels:
        app: pnr-resequencer-service-pod
    spec:
      volumes:
      - name: pnr-resequencer
        secret:
          secretName: pubsub-key    
      containers:
        - image: gcr.io/sab-ors-poc-sbx-01-9096/pnr-resequencer-service:latest
          name: pnr-resequencer-service
          resources:
          limits:
            cpu: 5000m
            ephemeral-storage: 2Gi
            memory: 2Gi
          requests:
            cpu: 5000m
            ephemeral-storage: 2Gi
            memory: 2Gi
          volumeMounts:
          - name: pnr-resequencer
            mountPath: /var/secrets/google
            readOnly: true
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
          - name: threadCount
            value: "50"
      
            