apiVersion: v1
kind: Service
metadata:
  name: pnr-resequencer-service
  labels:
    app: pnr-resequencer-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    app: pnr-resequencer-service-pod
  type: LoadBalancer