server:
  port: 8080

batch:
  size:
    limit: 1000

spanner:
  instance:
    id: instance-1
  database:
    id: database-1
  project:
    id: sab-order-service-sbx-7006
spring:
  application:
    name: et-finalization-service
    version: 0.0.1-init

topic:
  name:
    itinerary: projects/sab-order-service-sbx-7006/topics/itinerary-topic
    teleType : projects/sab-order-service-sbx-7006/topics/teleType-topic
    eticket : projects/sab-order-service-sbx-7006/topics/eticket-topic

