server.port: 9000

spring:
 profiles.active: emulator
 cloud:
   gcp:
     project-id: pnr-order-poc
     # credentials.location: file:C:\\Users\\ashu3\\AppData\\Roaming\\gcloud\\application_default_credentials.json
     spanner:
       instance-id: instance-1
       database: database-1



## logging
logging:
  pattern.console: '%d{yyyy-MM-dd HH:mm:ss} [%X{source}] [%X{correlation-id}] [%-5level] [%C:%L] - %m%n'
  file: logs/spanner-pollar-convereter-publisher/app.log
  level.org.springframework: info

# actuator properties
management:
  endpoints.web.exposure.include: '*'
  endpoint.health.show-details: always
  info.git.mode: full

info:
  app:
    name: spanner-pollar-convereter-publisher
    description: Google cloud spanner poller converter publisher
    version: 1.0.0
    java-vendor: ${java.specification.vendor}

app:
  topic.name: topic-1
---
spring.profiles: dev

---
spring.profiles: test

---
spring.profiles: prod

---
spring.profiles: emulator

spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 20
  cloud:
    gcp:
      project-id: pnr-order-poc
      spanner:
        emulator:
          enabled: true
        emulator-host: localhost:9010
        instance-id: instance-1
        database: database-1
      pubsub:
        emulator-host: localhost:8085